// Mock data for development and testing
export const mockEvents = [
  {
    id: "1",
    name: "Web Development Workshop",
    description: "Learn modern web development with React and Next.js",
    location: "Room 101",
    eventDate: new Date(2024, 10, 15),
    status: 1,
    eventTypeId: "1",
    totalAttendees: 45,
    presentAttendees: 42,
    absentAttendees: 3,
    eventSessions: [
      {
        id: "1",
        type: 1,
        startTime: "09:00 AM",
        endTime: "12:00 PM",
        requiresTimeOut: 1,
        allowEarlyTimeIn: 1,
        allowEarlyTimeOut: 1,
      },
      {
        id: "2",
        type: 2,
        startTime: "01:00 PM",
        endTime: "04:00 PM",
        requiresTimeOut: 1,
        allowEarlyTimeIn: 0,
        allowEarlyTimeOut: 0,
      },
    ],
  },
  {
    id: "2",
    name: "UI/UX Design Seminar",
    description: "Best practices in modern UI/UX design",
    location: "Room 202",
    eventDate: new Date(2024, 10, 16),
    status: 1,
    eventTypeId: "2",
    totalAttendees: 38,
    presentAttendees: 35,
    absentAttendees: 3,
    eventSessions: [
      {
        id: "3",
        type: 1,
        startTime: "10:00 AM",
        endTime: "01:00 PM",
        requiresTimeOut: 1,
        allowEarlyTimeIn: 1,
        allowEarlyTimeOut: 1,
      },
    ],
  },
]

export const mockStudents = [
  {
    id: "STU001",
    name: "John Doe",
    email: "john.doe@university.edu",
    course: "Computer Science",
    level: "3rd Year",
    avatar: "/placeholder.svg?key=adzm1",
  },
  {
    id: "STU002",
    name: "Jane Smith",
    email: "jane.smith@university.edu",
    course: "Information Technology",
    level: "2nd Year",
    avatar: "/placeholder.svg?key=tjbw4",
  },
  {
    id: "STU003",
    name: "Mike Johnson",
    email: "mike.johnson@university.edu",
    course: "Computer Science",
    level: "3rd Year",
    avatar: "/placeholder.svg?key=dv1ob",
  },
  {
    id: "STU004",
    name: "Sarah Williams",
    email: "sarah.williams@university.edu",
    course: "Software Engineering",
    level: "1st Year",
    avatar: "/diverse-students-studying.png",
  },
]

export const mockAttendanceRecords = [
  {
    id: "1",
    studentId: "STU001",
    eventId: "1",
    sessionType: "Morning",
    timeIn: "09:05 AM",
    timeOut: "12:00 PM",
    status: "On Time",
    method: "Face Recognition",
    timestamp: new Date(2024, 10, 15, 9, 5),
  },
  {
    id: "2",
    studentId: "STU002",
    eventId: "1",
    sessionType: "Morning",
    timeIn: "09:15 AM",
    timeOut: "12:05 PM",
    status: "Late",
    method: "Manual",
    timestamp: new Date(2024, 10, 15, 9, 15),
  },
  {
    id: "3",
    studentId: "STU003",
    eventId: "1",
    sessionType: "Afternoon",
    timeIn: "01:00 PM",
    timeOut: "04:00 PM",
    status: "On Time",
    method: "Face Recognition",
    timestamp: new Date(2024, 10, 15, 13, 0),
  },
  {
    id: "4",
    studentId: "STU004",
    eventId: "2",
    sessionType: "Morning",
    timeIn: "10:20 AM",
    timeOut: "01:00 PM",
    status: "Late",
    method: "Manual",
    timestamp: new Date(2024, 10, 16, 10, 20),
  },
]

export const mockDashboardStats = {
  totalEvents: 12,
  totalAttendees: 450,
  averageAttendance: 92.5,
  onTimePercentage: 87.3,
  lateArrivals: 12.7,
  totalSessions: 28,
  completedSessions: 24,
}

export const mockActivityFeed = [
  {
    id: "1",
    type: "attendance",
    title: "John Doe checked in",
    description: "Web Development Workshop - Morning Session",
    timestamp: new Date(Date.now() - 5 * 60000),
    status: "on-time",
  },
  {
    id: "2",
    type: "event",
    title: "UI/UX Design Seminar started",
    description: "Room 202 - 38 students registered",
    timestamp: new Date(Date.now() - 15 * 60000),
    status: "active",
  },
  {
    id: "3",
    type: "attendance",
    title: "Jane Smith checked in",
    description: "Web Development Workshop - Afternoon Session",
    timestamp: new Date(Date.now() - 25 * 60000),
    status: "late",
  },
  {
    id: "4",
    type: "event",
    title: "Web Development Workshop completed",
    description: "42 out of 45 students attended",
    timestamp: new Date(Date.now() - 2 * 60 * 60000),
    status: "completed",
  },
]
