import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { ReactQueryProvider } from "@/components/provider/react-query-provider";
import { ThemeProvider } from "@/components/provider/theme-provider";
import { AuthSessionProvider } from "@/components/provider/session-provider";
import { SessionCacheProvider } from "@/context/auth-context";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Face Mark",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <AuthSessionProvider>
                    <SessionCacheProvider>
                        <ThemeProvider
                            attribute="class"
                            defaultTheme="system"
                            enableSystem
                            disableTransitionOnChange
                        >
                            <ReactQueryProvider>
                                <div className="bg-background min-h-screen">
                                    {children}
                                </div>
                                <Toaster />
                            </ReactQueryProvider>
                        </ThemeProvider>
                    </SessionCacheProvider>
                </AuthSessionProvider>
            </body>
        </html>
    );
}
